services:
  db:
    image: postgres:15
    container_name: procedoc-db
    restart: always
    environment:
      POSTGRES_DB: procedoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: procedoc-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@procedoc.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres-data:
