spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/procedoc
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  api:
    security:
      token:
        secret: feijaocombanana



